# Generated by Django 3.2.6 on 2021-11-15 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=60)),
                ('editorial', models.CharField(max_length=60)),
                ('numpags', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numusuario', models.IntegerField(default=0)),
                ('nif', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPrestamo', models.DateTimeField()),
                ('fechaDevolucion', models.DateTimeField()),
                ('idlibro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.libro')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('idlibro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.libro')),
            ],
        ),
    ]
