# Generated by Django 3.2.6 on 2021-11-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='fechaDevolucion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='fechaPrestamo',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
